name: build

on:
  - pull_request
  - push

jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod a+x ./gradlew
      - name: build
        run: ./gradlew build
      - name: capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '16' }}
        uses: actions/upload-artifact@v2
        with:
          name: Build-Artifacts
          path: main/build/libs/
      - name: capture hexlanguage test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test-Artifacts-hexlanguage-${{ matrix.os }}-java-${{ matrix.java }}
          path: hexlanguage/build/reports/
      - name: capture nbt test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test-Artifacts-nbt-${{ matrix.os }}-java-${{ matrix.java }}
          path: nbt/build/reports/
      - name: capture nbtlanguage test artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Test-Artifacts-nbtlanguage-${{ matrix.os }}-java-${{ matrix.java }}
          path: nbtlanguage/build/reports/
