name: release-test

on:
#  push:
#    tags:
#      - 'v[0-9]+.[0-9]+.[0-9]+'
  - push

jobs:
  build:
    strategy:
      matrix:
        java: [ 16 ]
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    runs-on: ${{ matrix.os }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
      - name: validate gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - name: make gradle wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod a+x ./gradlew
      - name: jpackage image
        run: ./gradlew jpackageImage
      - name: list image contents
        run: ls -la main/build/jpackage
      - name: compress jpackage image *nix
        if: ${{ runner.os != 'Windows' }}
        working-directory: main/build/jpackage
        run: tar -czf NBTCoder.tgz NBTCoder/
      - name: compress jpackage image windows
        if: ${{ runner.os == 'Windows' }}
        uses: papeloto/action-zip@v1
        with:
          files: main/build/jpackage/NBTCoder/
          dest: main/build/jpackage/NBTCoder.zip
      - name: capture release test artifacts
        uses: actions/upload-artifact@v2
        with:
          name: Release-Build-Artifact
          path: main/build/jpackage/NBTCoder.*
